<?php

namespace Modules\UserManagement\Http\Controllers\Web\Admin;

use App\Http\Controllers\BaseController;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\View\View;
use Modules\TransactionManagement\Service\Interfaces\TransactionServiceInterface;
use Modules\TransactionManagement\Traits\TransactionTrait;
use Modules\UserManagement\Enums\SuspendReasonEnum;
use Modules\UserManagement\Service\Interfaces\DriverDetailServiceInterface;
use Modules\UserManagement\Service\Interfaces\DriverServiceInterface;

class CashCollectController extends BaseController
{
    use TransactionTrait;

    protected $driverService;
    protected $transactionService;
    protected $driverDetailService;

    public function __construct(DriverServiceInterface $driverService, TransactionServiceInterface $transactionService, DriverDetailServiceInterface $driverDetailService)
    {
        parent::__construct($driverService);
        $this->driverService = $driverService;
        $this->transactionService = $transactionService;
        $this->driverDetailService = $driverDetailService;
    }

    public function index(?Request $request, string $type = null): View|Collection|LengthAwarePaginator|null|callable|RedirectResponse
    {
        return parent::index($request, $type); // TODO: Change the autogenerated stub
    }

    public function show(string|int $id)
    {
        $driver = $this->driverService->findOne(id: $id);
        if ($driver) {
            $transactions = $this->transactionService->getBy(criteria: ['user_id' => $id, 'attribute' => 'admin_cash_collect'],orderBy: ['created_at'=>'desc'], limit: paginationLimit(), offset: 1);
            return view('usermanagement::admin.driver.withdraw.collect-cash', compact('driver', 'transactions'));
        }
        return redirect()->route('admin.drivers.index');


    }


    public function collect(string|int $id, Request $request)
    {
        $request->validate([
            'amount' => 'required|gt:0'
        ]);

        $driver = $this->driverService->findOne(id: $id, relations: ['userAccount', 'driverDetails']);
        if ($request->amount > ($driver?->userAccount?->payable_balance - $driver?->userAccount?->receivable_balance)) {

            Toastr::error(AMOUNT_400['message']);
            return back();
        }
        if ($driver?->userAccount?->receivable_balance == 0){
            $this->collectCashWithoutAdjustTransaction($driver, $request->amount);

        } elseif ($driver?->userAccount?->receivable_balance >0 && $driver?->userAccount?->payable_balance > $driver?->userAccount?->receivable_balance){
            $this->collectCashWithAdjustTransaction($driver, $request->amount);
        }

        $maximumCashInHandLimit = businessConfig('max_amount_to_hold_cash')?->value ?? 0;
        $collectableAmount = $driver?->userAccount->payable_balance > $driver?->userAccount->receivable_balance ? ($driver?->userAccount->payable_balance - $driver?->userAccount->receivable_balance) : 0;


        if ($maximumCashInHandLimit > $collectableAmount && $driver->driverDetails->is_suspended && $driver->driverDetails->suspend_reason == SuspendReasonEnum::CASH_IN_HAND_LIMIT->value)
        {
           $this->driverDetailService->updatedBy(criteria: ['user_id' => $driver->id], data: ['is_suspended' => 0, 'suspend_reason' => null]);
        }

        Toastr::success(DEFAULT_UPDATE_200['message']);

        return back();
    }
}
