<?php

namespace Modules\BusinessManagement\Http\Controllers\Web\Admin\PagesMedia;

use App\Http\Controllers\BaseController;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Http;
use Illuminate\View\View;
use Modules\BusinessManagement\Http\Requests\LandingBusinessStatisticsStoreOrUpdateRequest;
use Modules\BusinessManagement\Http\Requests\LandingCTAStoreOrUpdateRequest;
use Modules\BusinessManagement\Http\Requests\LandingCustomerAppDownloadStoreOrUpdateRequest;
use Modules\BusinessManagement\Http\Requests\LandingEarnMoneyStoreOrUpdateRequest;
use Modules\BusinessManagement\Http\Requests\LandingFooterStoreOrUpdateRequest;
use Modules\BusinessManagement\Http\Requests\LandingGalleryStoreOrUpdateRequest;
use Modules\BusinessManagement\Http\Requests\LandingIntroSectionStoreOrUpdateRequest;
use Modules\BusinessManagement\Http\Requests\LandingNewsletterStoreOrUpdateRequest;
use Modules\BusinessManagement\Http\Requests\LandingOurServicesSectionStoreOrUpdateRequest;
use Modules\BusinessManagement\Http\Requests\LandingOurSolutionsIntroUpdateRequest;
use Modules\BusinessManagement\Http\Requests\LandingOurSolutionsStoreOrUpdateRequest;
use Modules\BusinessManagement\Http\Requests\LandingTestimonialIntroStoreOrUpdateRequest;
use Modules\BusinessManagement\Http\Requests\LandingTestimonialStoreOrUpdateRequest;
use Modules\BusinessManagement\Service\Interfaces\BusinessSettingServiceInterface;
use Modules\BusinessManagement\Service\Interfaces\LandingPageSectionServiceInterface;

class LandingPageController extends BaseController
{
    protected $businessSettingService;
    protected $landingPageSectionService;

    public function __construct(BusinessSettingServiceInterface $businessSettingService, LandingPageSectionServiceInterface $landingPageSectionService)
    {
        parent::__construct($landingPageSectionService);
        $this->businessSettingService = $businessSettingService;
        $this->landingPageSectionService = $landingPageSectionService;
    }

    public function index(?Request $request, string $type = null): View|Collection|LengthAwarePaginator|null|callable|RedirectResponse
    {
        return parent::index($request, $type); // TODO: Change the autogenerated stub
    }

    public function introSection()
    {
        $this->authorize('business_view');
        $data = $this->landingPageSectionService->findOneBy(criteria: ['key_name' => INTRO_CONTENTS, 'settings_type' => INTRO_SECTION]);
        return view('businessmanagement::admin.pages.intro-section', compact('data'));
    }

    public function updateIntroSection(LandingIntroSectionStoreOrUpdateRequest $request): RedirectResponse
    {
        $this->authorize('business_edit');
        $this->landingPageSectionService->storeLandingPageIntroSection($request->validated());

        Toastr::success(LANDING_PAGE_INTRO_SECTION_UPDATE_200['message']);
        return back();
    }

    public function getOurSolutionsSectionView(Request $request): View
    {
        $this->authorize('business_view');
        $attributes = ['key_name' => INTRO_CONTENTS, 'settings_type' => OUR_SOLUTIONS_SECTION];
        $attributes1 = ['key_name' => SOLUTIONS, 'settings_type' => OUR_SOLUTIONS_SECTION];
        $introContents = $this->landingPageSectionService->findOneBy(criteria: $attributes);
        $isOurSolutionsEnabled = $this->landingPageSectionService->findOneBy(criteria: ['key_name' => 'is_our_solutions_enabled', 'settings_type' => OUR_SOLUTIONS_SECTION])?->value;
        $solutions = $this->landingPageSectionService->getBy(criteria: $attributes1, limit: paginationLimit(), offset: $request->get('page', 1));

        return view('businessmanagement::admin.pages.our-solutions', compact('introContents', 'solutions', 'isOurSolutionsEnabled'));
    }

    public function updateOurSolutions(LandingOurSolutionsIntroUpdateRequest $request): RedirectResponse
    {
        $this->authorize('business_edit');
        $this->landingPageSectionService->storeLandingPageOurSolutionsSection($request->validated());
        Toastr::success(LANDING_PAGE_OUR_SOLUTIONS_UPDATE_200['message']);
        return back();
    }

    public function getAddOrUpdateOurSolutions(LandingOurSolutionsStoreOrUpdateRequest $request): RedirectResponse
    {
        $this->authorize('business_edit');
        $data = $request->validated();
        if ($request->has('id')) {
            $data = array_merge($data, [
                'id' => $request['id']
            ]);
        }
        $this->landingPageSectionService->storeLandingPageOurSolutionsSection($data);
        Toastr::success(LANDING_PAGE_OUR_SOLUTIONS_UPDATE_200['message']);
        return redirect()->route('admin.business.pages-media.landing-page.our-solutions.index');
    }

    public function statusOurSolutions(Request $request): JsonResponse
    {
        $this->authorize('business_edit');
        $model = $this->landingPageSectionService->statusChangeOurSolutions(id: $request['id'], data: $request->all());
        
        return response()->json($model);
    }

    public function editOurSolutions($id)
    {
        $this->authorize('business_view');
        $attributes = ['id' => $id, 'key_name' => SOLUTIONS, 'settings_type' => OUR_SOLUTIONS_SECTION];
        $data = $this->landingPageSectionService->findOneBy(criteria: $attributes);
        return view('businessmanagement::admin.pages.edit-our-solutions', compact('data'));
    }

    public function deleteOurSolutions($id): RedirectResponse
    {
        $this->authorize('business_edit');
        $this->landingPageSectionService->deleteOurSolutions(id: $id);

        Toastr::success(OUR_SOLUTION_DELETE_200['message']);
        return back();
    }


    public function businessStatistics()
    {
        $this->authorize('business_view');
        $attributes = ['settings_type' => BUSINESS_STATISTICS, ['key_name', '!=', 'is_business_statistics_enabled']];
        $data = $this->landingPageSectionService->getBy(criteria: $attributes);

        $isBusinessStatisticsEnabled = $this->landingPageSectionService->findOneBy(criteria: ['key_name' => 'is_business_statistics_enabled', 'settings_type' => BUSINESS_STATISTICS])?->value;
        return view('businessmanagement::admin.pages.business-statistics', compact('data', 'isBusinessStatisticsEnabled'));
    }

    public function updateBusinessStatistics(LandingBusinessStatisticsStoreOrUpdateRequest $request)
    {
        $this->authorize('business_edit');
        $this->landingPageSectionService->storeLandingPageBusinessStatistics($request->validated());
        Toastr::success(LANDING_PAGE_BUSINESS_STATISTICS_UPDATE_200['message']);
        return back();
    }

    public function getOurServicesView()
    {
        $this->authorize('business_view');
        $attributes = ['key_name' => INTRO_CONTENTS, 'settings_type' => OUR_SERVICES];
        $attributes1 = ['settings_type' => OUR_SERVICES, ['key_name', '!=', 'is_our_services_enabled'], ['key_name', '!=', 'intro_contents']];
        $introContents = $this->landingPageSectionService->findOneBy(criteria: $attributes);
        $isOurServicesEnabled = $this->landingPageSectionService->findOneBy(criteria: ['key_name' => 'is_our_services_enabled', 'settings_type' => OUR_SERVICES])?->value;
        $services = $this->landingPageSectionService->getBy(criteria: $attributes1);

        return view('businessmanagement::admin.pages.our-services', compact('introContents', 'isOurServicesEnabled', 'services'));
    }

    public function updateOurServicesSection(LandingOurServicesSectionStoreOrUpdateRequest $request): RedirectResponse
    {
        $this->authorize('business_edit');
        $this->landingPageSectionService->storeLandingPageOurServicesSection($request->validated());
        Toastr::success(LANDING_PAGE_OUR_SERVICES_UPDATE_200['message']);
        return back();
    }

    public function ourPlatform()
    {
        return view('businessmanagement::admin.pages.our-platform');
    }

    public function updateOurPlatform(Request $request)
    {
        Toastr::success(LANDING_PAGE_UPDATE_200['message']);
        return back();
    }

    public function earnMoney()
    {
        $this->authorize('business_view');
        $attributes = ['key_name' => INTRO_CONTENTS, 'settings_type' => EARN_MONEY];
        $attributes1 = ['key_name' => BUTTON_CONTENTS, 'settings_type' => EARN_MONEY];
        $introContents = $this->landingPageSectionService->findOneBy(criteria: $attributes);
        $buttonContents = $this->landingPageSectionService->findOneBy(criteria: $attributes1);
        $isEarnMoneyEnabled = $this->landingPageSectionService->findOneBy(criteria: ['key_name' => 'is_earn_money_enabled', 'settings_type' => EARN_MONEY])?->value;

        return view('businessmanagement::admin.pages.earn-money', compact('introContents', 'buttonContents', 'isEarnMoneyEnabled'));
    }

    public function updateEarnMoneySection(LandingEarnMoneyStoreOrUpdateRequest $request): RedirectResponse
    {
        $this->authorize('business_edit');
        $this->landingPageSectionService->storeLandingPageEarnMoneySection($request->validated());
        Toastr::success(LANDING_PAGE_EARN_MONEY_UPDATE_200['message']);
        return back();
    }

    public function updateEarnMoney(LandingEarnMoneyStoreOrUpdateRequest $request)
    {
        $this->authorize('business_edit');
        $this->businessSettingService->storeLandingPageEarnMoney($request->validated());
        Toastr::success(LANDING_PAGE_UPDATE_200['message']);
        return back();
    }

    public function testimonial(Request $request)
    {
        $this->authorize('business_view');
        $attributes = ['key_name' => 'reviews', 'settings_type' => TESTIMONIAL];
        $testimonials = $this->landingPageSectionService->getBy(criteria: $attributes, limit: paginationLimit(), offset: $request->get('page', 1));
        $isTestimonialEnabled = $this->landingPageSectionService->findOneBy(criteria: ['key_name' => 'is_testimonial_enabled', 'settings_type' => TESTIMONIAL])?->value;
        $introContents = $this->landingPageSectionService->findOneBy(criteria: ['key_name' => INTRO_CONTENTS, 'settings_type' => TESTIMONIAL]);
        return view('businessmanagement::admin.pages.testimonial', compact('testimonials', 'isTestimonialEnabled', 'introContents'));
    }

    public function updateTestimonialIntro(LandingTestimonialIntroStoreOrUpdateRequest $request)
    {
        $this->authorize('business_edit');
        $introContents = $this->landingPageSectionService->findOneBy(criteria: ['key_name' => INTRO_CONTENTS, 'settings_type' => TESTIMONIAL]);
        $data = ['key_name' => INTRO_CONTENTS, 'settings_type' => TESTIMONIAL, 'value' => ['title' => $request->title]];

        if ($introContents) {
            $this->landingPageSectionService->update(id: $introContents->id, data: $data);
        } else {
            $this->landingPageSectionService->create(data: $data);
        }

        Toastr::success(TESTIMONIAL_INTRO_UPDATE_200['message']);

        return back();
    }

    public function updateTestimonial(LandingTestimonialStoreOrUpdateRequest $request)
    {
        $this->authorize('business_edit');
        $data = $request->validated();
        if ($request->has('id')) {
            $data = array_merge($data, [
                'id' => $request->id
            ]);
        }
        $this->landingPageSectionService->storeLandingPageTestimonial($data);
        Toastr::success(LANDING_PAGE_UPDATE_200['message']);
        return redirect()->route('admin.business.pages-media.landing-page.testimonial.index');
    }

    public function statusTestimonial(Request $request)
    {
        $this->authorize('business_edit');
        $model = $this->landingPageSectionService->statusChange(id: $request->id, data: $request->all());
        return response()->json($model);
    }

    public function editTestimonial($id)
    {
        $this->authorize('business_view');
        $attributes = ['id' => $id, 'key_name' => 'reviews', 'settings_type' => TESTIMONIAL];
        $data = $this->landingPageSectionService->findOneBy(criteria: $attributes);
        return view('businessmanagement::admin.pages.edit-testimonial', compact('data'));
    }

    public function deleteTestimonial($id)
    {
        $this->authorize('business_edit');
        $this->landingPageSectionService->delete(id: $id);

        Toastr::success(TESTIMONIAL_DELETE_200['message']);
        return back();
    }

    public function cta()
    {
        $this->authorize('business_view');
        $attributes = ['key_name' => CTA, 'settings_type' => LANDING_PAGES_SETTINGS];
        $attributes1 = ['key_name' => CTA_IMAGE, 'settings_type' => LANDING_PAGES_SETTINGS];
        $data = $this->businessSettingService->findOneBy(criteria: $attributes);
        $data1 = $this->businessSettingService->findOneBy(criteria: $attributes1);
        return view('businessmanagement::admin.pages.cta', compact('data', 'data1'));
    }

    public function updateCta(LandingCTAStoreOrUpdateRequest $request)
    {
        $this->authorize('business_edit');
        $this->businessSettingService->storeLandingPageCTA($request->validated());
        $activationMode = externalConfig('activation_mode');
        $martBaseUrl = externalConfig('mart_base_url');
        if ($activationMode && $activationMode->value == 1 && $martBaseUrl && $martBaseUrl->value != null) {
            $name = businessConfig('business_name', BUSINESS_INFORMATION)?->value ?? "DriveMond";
            $logo = businessConfig('header_logo', BUSINESS_INFORMATION)?->value ? asset(businessConfig('header_logo', BUSINESS_INFORMATION)?->value) : dynamicAsset('public/assets/admin-module/img/logo.png');
            $cta = $this->businessSettingService->findOneBy(criteria: ['key_name' => CTA, 'settings_type' => LANDING_PAGES_SETTINGS]);

            try {
                $response = Http::post($martBaseUrl->value . '/api/v1/configurations/store', [
                    'drivemond_business_name' => $name,
                    'drivemond_business_logo' => $logo,
                    'drivemond_app_url_android' => $cta?->value && $cta?->value['play_store']['user_download_link'] ? $cta?->value['play_store']['user_download_link'] : "",
                    'drivemond_app_url_ios' => $cta?->value && $cta?->value['app_store']['user_download_link'] ? $cta?->value['app_store']['user_download_link'] : "",
                ]);
            } catch (\Exception $exception) {

            }
        }
        Toastr::success(LANDING_PAGE_UPDATE_200['message']);
        return back();
    }

    public function gallery()
    {
        $this->authorize('business_view');
        $attributes = ['settings_type' => GALLERY, ['key_name', '!=', 'is_gallery_enabled']];
        $isGalleryEnabled = $this->landingPageSectionService->findOneBy(criteria: ['key_name' => 'is_gallery_enabled', 'settings_type' => GALLERY])?->value;
        $cards = $this->landingPageSectionService->getBy(criteria: $attributes);

        return view('businessmanagement::admin.pages.gallery', compact('isGalleryEnabled', 'cards'));
    }

    public function updateGallerySection(LandingGalleryStoreOrUpdateRequest $request): RedirectResponse
    {
        $this->authorize('business_edit');
        $this->landingPageSectionService->storeLandingPageGallerySection($request->validated());
        Toastr::success(LANDING_PAGE_GALLERY_UPDATE_200['message']);
        return back();
    }

    public function customerAppDownload()
    {
        $this->authorize('business_view');
        $attributes = ['key_name' => INTRO_CONTENTS, 'settings_type' => CUSTOMER_APP_DOWNLOAD];
        $attributes1 = ['key_name' => BUTTON_CONTENTS, 'settings_type' => CUSTOMER_APP_DOWNLOAD];
        $isCustomerAppDownloadEnabled = $this->landingPageSectionService->findOneBy(criteria: ['key_name' => 'is_customer_app_download_enabled', 'settings_type' => CUSTOMER_APP_DOWNLOAD])?->value;
        $introContents = $this->landingPageSectionService->findOneBy(criteria: $attributes);
        $buttonContents = $this->landingPageSectionService->findOneBy(criteria: $attributes1);

        return view('businessmanagement::admin.pages.customer-app-download', compact('isCustomerAppDownloadEnabled', 'introContents', 'buttonContents'));
    }

    public function updateCustomerAppDownloadSection(LandingCustomerAppDownloadStoreOrUpdateRequest $request): RedirectResponse
    {
        $this->authorize('business_edit');
        $this->landingPageSectionService->storeLandingPageCustomerAppDownloadSection($request->validated());

        Toastr::success(LANDING_PAGE_CUSTOMER_APP_DOWNLOAD_UPDATE_200['message']);

        return back();
    }

    public function newsletter()
    {
        $this->authorize('business_view');
        $isNewsletterEnabled = $this->landingPageSectionService->findOneBy(criteria: ['key_name' => 'is_newsletter_enabled', 'settings_type' => NEWSLETTER])?->value;
        $attributes = ['key_name' => INTRO_CONTENTS, 'settings_type' => NEWSLETTER];
        $introContents = $this->landingPageSectionService->findOneBy(criteria: $attributes);

        return view('businessmanagement::admin.pages.newsletter', compact('isNewsletterEnabled', 'introContents'));
    }

    public function updateNewsletterSection(LandingNewsletterStoreOrUpdateRequest $request): RedirectResponse
    {
        $this->authorize('business_edit');
        $this->landingPageSectionService->storeLandingNewsletterSection($request->validated());
        Toastr::success(LANDING_PAGE_NEWSLETTER_UPDATE_200['message']);
        return back();
    }

    public function footer()
    {
        $this->authorize('business_view');
        $isFooterEnabled = $this->landingPageSectionService->findOneBy(criteria: ['key_name' => 'is_newsletter_enabled', 'settings_type' => NEWSLETTER])?->value;
        $attributes = ['key_name' => FOOTER_CONTENTS, 'settings_type' => FOOTER];
        $footerContents = $this->landingPageSectionService->findOneBy(criteria: $attributes);

        return view('businessmanagement::admin.pages.footer', compact('isFooterEnabled', 'footerContents'));
    }

    public function updateFooterSection(LandingFooterStoreOrUpdateRequest $request): RedirectResponse
    {
        $this->authorize('business_edit');
        $this->landingPageSectionService->storeLandingFooterSection($request->validated());
        Toastr::success(LANDING_PAGE_FOOTER_UPDATE_200['message']);

        return back();
    }

    public function updateLandingPageSetting(Request $request): JsonResponse
    {
        $this->authorize('business_edit');
        $landingPageInfo = $this->landingPageSectionService->findOneBy(criteria: ['key_name' => $request['name'], 'settings_type' => $request['type']]);
        if ($landingPageInfo) {
            $data = $this->landingPageSectionService
                ->update(id: $landingPageInfo->id, data: ['key_name' => $request['name'], 'settings_type' => $request['type'], 'value' => $request['value']]);
        } else {
            $data = $this->landingPageSectionService
                ->create(data: ['key_name' => $request['name'], 'settings_type' => $request['type'], 'value' => $request['value']]);
        }

        return response()->json($data);
    }
}
